name: acwadcom
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+5

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #For UI
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.1.12
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  floating_bottom_bar: ^0.0.3
  flutter_spinkit: ^5.2.0
  cached_network_svg_image: ^1.1.0
  # image: ^4.3.0



  #State Managment
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed: ^2.5.0
  freezed_annotation: ^2.4.2

  #Check Internt
  flutter_offline: 3.0.1


  #local Storage 
  get_storage: ^2.1.1
  shared_preferences: ^2.3.2
  

  
  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  internet_connection_checker_plus: ^2.0.0
  connectivity_plus: 5.0.2


  # Firebase
  firebase_core: 3.4.1
  cloud_firestore: 5.4.1
  firebase_auth: ^5.0.0
  firebase_storage: ^12.1.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  extended_image: ^8.2.1
#  firebase_pagination: ^4.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: ^2.0.5
  adoptive_calendar: ^0.1.9
  json_annotation: ^4.9.0
  get_it: ^8.0.0
  # flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  image: ^4.3.0
  intl_phone_number_input_v2: ^0.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.11
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_app_acwdcom.png"
  adaptive_icon_background: "#08242A"
  adaptive_icon_foreground: "assets/images/foreground_logo.png"
  min_sdk_android: 21
    

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/lang/
    - assets/lottie/
    - assets/animations/
    


  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
