// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  /*

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:"AIzaSyDEsuC-rOx0AgW5rksnMrMPoN7VdWpjjQo",
    appId: "1:242503319267:android:4c2cd1f1fed510ab3e4fd6",
    messagingSenderId: "242503319267",
    projectId: "acwadcom-8ab26",
    // storageBucket: 'flutter-app-distribution-622c3.appspot.com',
  );
  
  */



  static const FirebaseOptions android = FirebaseOptions(
    apiKey:"AIzaSyDEsuC-rOx0AgW5rksnMrMPoN7VdWpjjQo",
    appId: "1:242503319267:android:b11a9ec439d30bba3e4fd6",
    messagingSenderId: "242503319267",
    projectId: "acwadcom-8ab26",
    storageBucket:"acwadcom-8ab26.appspot.com"
    // storageBucket: 'flutter-app-distribution-622c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    
    apiKey: "AIzaSyBJ_s7nyp4dzOlnz3uYaHi06-3VM3K12SM",
    appId: '1:242503319267:ios:1644c586dce795e23e4fd6',
    messagingSenderId: "242503319267",
    projectId: "acwadcom-8ab26",
    storageBucket: "acwadcom-8ab26.appspot.com",
    iosBundleId: 'com.mohamed.acwdcoom',
  );
}